config/routes.rb
Rails.application.routes.draw do

  resources :sessions
  get 'sessions/new'

  get 'auth/facebook/callback', to: 'sessions#create'
  get 'auth/failure', to: redirect('/')

  resources :users
  get 'tags/:tag', to: 'posts#index', as: "tag"
  resources :posts, only: [:create]
  root 'posts#index'
end

app/models/add_column_to_user.rb
class AddColumnToUser < ApplicationRecord
end

app/models/application_record.rb
class ApplicationRecord < ActiveRecord::Base
  self.abstract_class = true
end

app/models/post.rb
class Post < ApplicationRecord

     has_many :taggings
     has_many :tags, through: :taggings

     def all_tags=(names)
          self.tags = names.split(", ").map do |name|
               Tag.where(name: name.strip).first_or_create!
          end
     end

     def all_tags
          self.tags.map(&:name).join(", ")
     end

     def self.tagged_with(name)
          Tag.find_by_name!(name).posts
     end

end

app/models/tag.rb
class Tag < ApplicationRecord

     has_many :taggings
     has_many :posts, through: :taggings

     def self.counts
          self.select("name, count(taggings.tag_id) as count").joins(:taggings).group("taggings.tag_id")
     end
end

app/models/tagging.rb
class Tagging < ApplicationRecord
  belongs_to :post
  belongs_to :tag
end

app/models/user.rb
class User < ApplicationRecord
     has_secure_password
     def self.create_with_omniauth(auth)

       user = find_or_create_by(uid: auth['uid'], provider:  auth['provider'])
       user.email = "#{auth['uid']}@#{auth['provider']}.com"
       user.password = auth['uid']
       user.name = auth['info']['name']
       if User.exists?(user)
         user
       else
         user.save!
         user
       end
     end
end

app/controllers/add_column_to_users_controller.rb
class AddColumnToUsersController < ApplicationController
end

app/controllers/application_controller.rb
class ApplicationController < ActionController::Base
  protect_from_forgery with: :exception
end

app/controllers/posts_controller.rb
class PostsController < ApplicationController
  def index
       if params[:tag]
            @post = Post.tagged_with(params[:tag])
       else
            @post = Post.all
       end
  end

  def create
       @post = Post.new(post_params)
       respond_to do |format|
            if @post.save
                 format.js
            else
                 format.html { redner root_path}
            end
       end
  end

  private

  def post_params
       params.require(:post).permit(:author, :content, :all_tags)
  end
end

app/controllers/sessions_controller.rb
class SessionsController < ApplicationController
  def new
  end

  def create
       if request.env['omniauth.auth']
         user = User.create_with_omniauth(request.env['omniauth.auth'])
         session[:user_id] = user.id
         redirect_to user_path(user.id)
       else
         user = User.find_by_email(params[:email])
         user && user.authenticate(params[:password])
         session[:user_id] = user.id
         redirect_to user_path(user.id)
       end
  end
end

app/controllers/users_controller.rb
class UsersController < ApplicationController
  before_action :set_user, only: [:show, :edit, :update, :destroy]

  # GET /users
  # GET /users.json
  def index
    @users = User.all
  end

  # GET /users/1
  # GET /users/1.json
  def show
  end

  # GET /users/new
  def new
    @user = User.new
  end

  # GET /users/1/edit
  def edit
  end

  # POST /users
  # POST /users.json
  def create
    @user = User.new(allowed_params)
    if @user.save
      redirect_to root_url, notice: 'Thank you for signing up!'
    else
      render :new
    end
  end

  # PATCH/PUT /users/1
  # PATCH/PUT /users/1.json
  def update
    respond_to do |format|
      if @user.update(user_params)
        format.html { redirect_to @user, notice: 'User was successfully updated.' }
        format.json { render :show, status: :ok, location: @user }
      else
        format.html { render :edit }
        format.json { render json: @user.errors, status: :unprocessable_entity }
      end
    end
  end

  # DELETE /users/1
  # DELETE /users/1.json
  def destroy
    @user.destroy
    respond_to do |format|
      format.html { redirect_to users_url, notice: 'User was successfully destroyed.' }
      format.json { head :no_content }
    end
  end

  private
    # Use callbacks to share common setup or constraints between actions.
    def set_user
      @user = User.find(params[:id])
    end

    # Never trust parameters from the scary internet, only allow the white list through.
    def allowed_params
      params.require(:user).permit(:name, :email, :password_digest, :provider, :uid)
    end
end

app/helpers/add_column_to_users_helper.rb
module AddColumnToUsersHelper
end

app/helpers/application_helper.rb
module ApplicationHelper
end

app/helpers/posts_helper.rb
module PostsHelper
     def tag_links(tags)
          tags.split(", ").map{|tag| link_to tag.strip, tag_path(tag.strip)}.join(", ")
     end

     def tag_cloud(tags, classes)
          max = tags.sort_by(&:count).last
          tags.each do |tag|
               index = tag.count.to_f/max.count * (classes.size-1)
               yield(tag, classes[index.round])
          end
     end
end

app/helpers/sessions_helper.rb
module SessionsHelper
end

app/helpers/users_helper.rb
module UsersHelper
end

app/views/layouts/application.html.erb
<!DOCTYPE html>
<html lang="en">
  <head>
    <meta charset="utf-8" />
    <meta name="viewport" content="width=device-width, initial-scale=1.0" />

    <title><%= content_for?(:title) ? yield(:title) : "foundation-rails" %></title>

    <%= stylesheet_link_tag    "application" %>
    <%= javascript_include_tag "vendor/modernizr" %>
    <%= csrf_meta_tags %>
  </head>

  <body>
     <div id="user_header">
          <%= link_to "Sign Up", new_user_path %>
          <%= link_to "Log In", new_session_path %>
     </div>

    <%= yield %>
    <%= javascript_include_tag "application" %>
  </body>
</html>

app/views/posts/_new.html.erb
<div class="row text-center">
     <%= form_for(Post.new, remote: true) do |f| %>
     <div class="large-10 large-centered columns">
          <%= f.text_field :author, placeholder: "Author name" %>
     </div>
     <div class="large-10 large-centered columns">
          <%= f.text_area :content, placeholder: "Your post", rows: 5 %>
     </div>
     <div class="large-10 large-centered columns">
          <%= f.text_field :all_tags, placeholder: "Tags seperated by comma" %>
     </div>
     <div class="large-10 large-centered columns">
          <%= f.submit "Post", class: "button" %>
     </div>
     <% end %>
</div>
<!-- I'm Here To Stay!!! -->

app/views/posts/_post.html.erb
<%= div_for post do %>
     <div class="large-12 columns border border-box glassy-bg mt pt">
          <strong><%= h(post.author) %></strong><br>
          <sup class"text-muted">From <%= time_ago_in_words(post.created_at) %></sup><br>
          <div class="mb pb">
               <%= h(post.content) %>
          </div>
          <div class="tags">
               <%= raw tag_links(post.all_tags) %>
          </div>
     </div>
     <% end %>

app/views/posts/create.html.erb
<h1>Posts#create</h1>
<p>Find me in app/views/posts/create.html.erb</p>

app/views/posts/index.html.erb
<div class="row mt pt">
     <div class="large-5 columns">
          <div class="top-pad glassy-bg">
               <%= render partial: "posts/new" %>
          </div>
          <div class="tags-clouds galssy-bg">
               <h4>Tags Cloud</h4>
               <% tag_cloud Tag.counts, %w{css1 css2 css3 css4} do |tag,css_class| %>
               <%= link_to tag.name, tag_path(tag.name), class: css_class %>
               <% end %>
          </div>
     </div>
     <div class="large-7 columns" id="posts">
          <%= render partial: @post.reverse %>
     </div>
</div>

app/views/users/_form.html.erb
<%= form_with(model: user, local: true) do |form| %>
  <% if user.errors.any? %>
    <div id="error_explanation">
      <h2><%= pluralize(user.errors.count, "error") %> prohibited this user from being saved:</h2>

      <ul>
      <% user.errors.full_messages.each do |message| %>
        <li><%= message %></li>
      <% end %>
      </ul>
    </div>
  <% end %>

  <div class="field">
    <%= form.label :name %>
    <%= form.text_field :name, id: :user_name %>
  </div>

  <div class="field">
    <%= form.label :email %>
    <%= form.text_field :email, id: :user_email %>
  </div>

  <div class="field">
    <%= form.label :password %>
    <%= form.text_field :password, id: :user_password %>
  </div>

  <div class="field">
    <%= form.label :provider %>
    <%= form.text_field :provider, id: :user_provider %>
  </div>

  <div class="field">
    <%= form.label :uid %>
    <%= form.text_field :uid, id: :user_uid %>
  </div>

  <div class="actions">
    <%= form.submit %>
  </div>
<% end %>

app/views/users/edit.html.erb
<h1>Editing User</h1>

<%= render 'form', user: @user %>

<%= link_to 'Show', @user %> |
<%= link_to 'Back', users_path %>

app/views/users/index.html.erb
<p id="notice"><%= notice %></p>

<h1>Users</h1>

<table>
  <thead>
    <tr>
      <th>Name</th>
      <th>Email</th>
      <th>Password</th>
      <th>Provider</th>
      <th>Uid</th>
      <th colspan="3"></th>
    </tr>
  </thead>

  <tbody>
    <% @users.each do |user| %>
      <tr>
        <td><%= user.name %></td>
        <td><%= user.email %></td>
        <td><%= user.password %></td>
        <td><%= user.provider %></td>
        <td><%= user.uid %></td>
        <td><%= link_to 'Show', user %></td>
        <td><%= link_to 'Edit', edit_user_path(user) %></td>
        <td><%= link_to 'Destroy', user, method: :delete, data: { confirm: 'Are you sure?' } %></td>
      </tr>
    <% end %>
  </tbody>
</table>

<br>

<%= link_to 'New User', new_user_path %>

app/views/users/new.html.erb
<h1>Sign Up</h1>
<%= form_for @user do |f| %>
  <% if @user.errors.any? %>
    <div class="error_messages">
      <h2>Form is invalid</h2>
      <ul>
        <% @user.errors.full_messages.each do |message| %>
          <li><%= message %></li>
        <% end %>
      </ul>
    </div>
  <% end %>

  <div class="field">
    <%= f.label :email %><br />
    <%= f.text_field :email %>
  </div>
  <div class="field">
    <%= f.label :password %><br />
    <%= f.password_field :password_digest %>
  </div>
  <div class="field">
    <%= f.label :password_confirmation %><br />
    <%= f.password_field :password_digest_confirmation %>
  </div>
  <div class="actions"><%= f.submit "Sign Up" %></div>
<% end %>

app/views/users/show.html.erb
<p id="notice"><%= notice %></p>

<p>
  <strong>Name:</strong>
  <%= @user.name %>
</p>

<p>
  <strong>Email:</strong>
  <%= @user.email %>
</p>

<p>
  <strong>Password:</strong>
  <%= @user.password %>
</p>

<p>
  <strong>Provider:</strong>
  <%= @user.provider %>
</p>

<p>
  <strong>Uid:</strong>
  <%= @user.uid %>
</p>

<%= link_to 'Edit', edit_user_path(@user) %> |
<%= link_to 'Back', users_path %>